### ISSUE TITLE
Video/GIF version of the downloader

### ISSUE THREAD

**Issue by Tim3Game** [kniffen/Web-Audio-Downloader#1]
Hello,
I know that this is a Audio only downloader, but I really like how it works, the simplicity of it and mainly the ability to select the times of which the audio file should be. And I wanted to ask, if it would be possible to create or add the functionality of having the option of downloading a video file or with the timestamp feature the ability to create gifs for instance of YT videos. If it would be all in one app, it would be maybe the best program out there that does all of this. I already use a program for downloading YT videos, but I don't like how it works: You need to insert the video, then select the format and folder where it should be and then download it, and when it don't works, you need to re-download the app that is used for downloading videos. And even when it downloads, it always shows something like: Error or Warning as an status. It would be much simpler and better simply to, for instance, insert the URL, add it to queue, select for every video what "Download Profile" you want (A profile would be a set of rules on what the format should be (.mp3, .wav, .mp4), where it should save and maybe other things like different Title format or so, but) and simply download it.

**Comment by kniffen** [comment]
As you pointed out this app is for audio only.
However the technologies it uses are mainly made for video, so making a fork that does this would be trivial.
I have no current plans of doing this though, but if interested you can check out [youtube-dl](https://ytdl-org.github.io/youtube-dl/) and [ffmpeg](https://ffmpeg.org/) to do what you need in a terminal.
